### ISSUE TITLE
Rewrite the data storage

### ISSUE THREAD

**Issue by SleepySwords** [SleepySwords/do_todo#26]
Data should not be stored in `.config`.

**Comment by Froloket64** [comment]
Where do you think it would be better to store it in: `.local` or `.cache`? Or a `$HOME/.dotodo`?

**Comment by SleepySwords** [comment]
I think it'd probably be best to store in `$HOME/.dotodo`, just to allow easier access to that data. I was thinking that we should probably let the user select where. But `$HOME/.dotodo` would be a nice default.

**Comment by Froloket64** [comment]
You know, the only opposition I have to `$HOME/.dotodo` is that, at least to me (and I've heard multiple people saying this), it's annoying how the home dir gets cluttered by "dotdirs". If we put the data in `.local/share/dotodo` it wouldn't contribute to such a situation.

Also, why do you think we should give users access to internal task storage? I mean, nothing wrong with that, but it still seems like something that maybe only power-users would be interested in. Besides maybe uses for synchronization, but as far as I understand, you're planning on implementing some sync in the app, so that shouldn't matter.

**Comment by SleepySwords** [comment]
> If we put the data in .local/share/dotodo it wouldn't contribute to such a situation.

That should be fine if it was mentioned somewhere in the README.md

> Besides maybe uses for synchronization, but as far as I understand, you're planning on implementing some sync in the app, so that shouldn't matter.

It was more for allowing users to be able to backup their data locally if they wish to do so.

**Comment by Froloket64** [comment]
> It was more for allowing users to be able to backup their data locally if they wish to do so.

Hm, okay, but I think just noting the location somewhere (e.g. `README.md) should be fine.
